import { useState, useRef, useEffect } from 'react'
import { ethers } from 'ethers'
import { KeyIcon } from '../components/icons'
import './StealthWallet.css'

function copyToClipboard(text, setCopied, key) {
    navigator.clipboard.writeText(text).then(() => {
        setCopied(key)
        setTimeout(() => setCopied(''), 2000)
    })
}

export default function StealthWallet() {
    const [wallets, setWallets] = useState([])
    const [count, setCount] = useState(1)
    const [vanityPrefix, setVanityPrefix] = useState('')
    const [isMining, setIsMining] = useState(false)
    const [attempts, setAttempts] = useState(0)
    const [revealed, setRevealed] = useState({})
    const [copied, setCopied] = useState('')
    const miningRef = useRef(false)

    // Cleanup on unmount
    useEffect(() => {
        return () => {
            miningRef.current = false
        }
    }, [])

    function generateWallets() {
        if (isMining) {
            miningRef.current = false
            setIsMining(false)
            return
        }

        const prefix = vanityPrefix.trim().toLowerCase()
        if (prefix) {
            // Validate hex chars only
            if (!/^[0-9a-f]+$/i.test(prefix)) {
                alert('Prefix must only contain hex characters (0-9, a-f, A-F)')
                return
            }
            startMining(prefix)
            return
        }

        // Standard generation
        const generated = Array.from({ length: count }, () => {
            const w = ethers.Wallet.createRandom()
            return {
                id: crypto.randomUUID(),
                address: w.address,
                privateKey: w.privateKey,
                mnemonic: w.mnemonic.phrase,
            }
        })
        setWallets(generated)
        setRevealed({})
    }

    function startMining(prefix) {
        setIsMining(true)
        setAttempts(0)
        miningRef.current = true
        setWallets([])
        setRevealed({})

        const foundWallets = []
        let currentAttempts = 0
        const batchSize = 100 // Balance between speed and UI responsiveness

        function mineBatch() {
            if (!miningRef.current) return

            for (let i = 0; i < batchSize; i++) {
                const w = ethers.Wallet.createRandom()
                // Check if address (excluding '0x') starts with prefix
                if (w.address.toLowerCase().slice(2).startsWith(prefix)) {
                    foundWallets.push({
                        id: crypto.randomUUID(),
                        address: w.address,
                        privateKey: w.privateKey,
                        mnemonic: w.mnemonic.phrase,
                    })

                    if (foundWallets.length >= count) {
                        setWallets(foundWallets)
                        setIsMining(false)
                        miningRef.current = false
                        return
                    }
                }
            }

            currentAttempts += batchSize
            setAttempts(currentAttempts)

            // Yield to main thread then continue mining
            if (miningRef.current) {
                setTimeout(mineBatch, 0)
            }
        }

        // Start the loop
        setTimeout(mineBatch, 0)
    }

    function toggleReveal(id, field) {
        setRevealed(r => ({ ...r, [`${id}-${field}`]: !r[`${id}-${field}`] }))
    }

    function downloadJSON(wallet) {
        const data = {
            address: wallet.address,
            privateKey: wallet.privateKey,
            mnemonic: wallet.mnemonic,
            generatedAt: new Date().toISOString(),
            warning: 'KEEP THIS FILE PRIVATE. NEVER SHARE IT. Generated by Anonastr — client-side only.',
        }
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `Anonastr-wallet-${wallet.address.slice(0, 8)}.json`
        a.click()
        URL.revokeObjectURL(url)
    }

    return (
        <div className="page fade-up">
            <h1 className="page-title">Stealth Wallet Generator</h1>
            <p className="page-subtitle">Generate fresh burner wallets entirely in your browser. Nothing ever leaves your device.</p>

            <div className="alert alert-warning" style={{ marginBottom: 24, alignItems: 'flex-start' }}>
                <KeyIcon style={{ width: 22, height: 22, flexShrink: 0, marginTop: 2, stroke: '#fcd34d' }} />
                <div>
                    <strong>100% Client-Side:</strong> All wallets are generated locally using cryptographically secure randomness. No data is sent to any server. Anonastr cannot see your keys.
                </div>
            </div>

            <div className="card">
                <div style={{ display: 'flex', gap: 12, alignItems: 'flex-end', flexWrap: 'wrap' }}>
                    <div className="input-group" style={{ flex: 1, marginBottom: 0 }}>
                        <label className="input-label">Number of Wallets</label>
                        <select
                            className="input"
                            value={count}
                            onChange={e => setCount(Number(e.target.value))}
                            disabled={isMining}
                        >
                            {[1, 2, 3, 5].map(n => <option key={n} value={n}>{n} wallet{n > 1 ? 's' : ''}</option>)}
                        </select>
                    </div>

                    <div className="input-group" style={{ flex: 1, marginBottom: 0 }}>
                        <label className="input-label">Vanity Prefix (Optional)</label>
                        <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
                            <span style={{ position: 'absolute', left: 12, color: 'var(--text-secondary)' }}>0x</span>
                            <input
                                className="input"
                                value={vanityPrefix}
                                onChange={e => setVanityPrefix(e.target.value)}
                                placeholder="anon"
                                disabled={isMining}
                                style={{ paddingLeft: 34, width: '100%' }}
                            />
                        </div>
                    </div>

                    <button
                        className={`btn ${isMining ? 'btn-secondary' : 'btn-primary'}`}
                        style={{ height: 50, minWidth: 140 }}
                        onClick={generateWallets}
                    >
                        {isMining ? (
                            <>Stop Mining</>
                        ) : (
                            <><KeyIcon color="black" style={{ width: 18, height: 18 }} /> {vanityPrefix ? 'Mine Wallets' : 'Generate'}</>
                        )}
                    </button>
                </div>

                {isMining && (
                    <div className="alert alert-info fade-up" style={{ marginTop: 16 }}>
                        <span className="loader" style={{ width: 16, height: 16 }} />
                        Mining vanity addresses starting with "0x{vanityPrefix.toLowerCase()}"...
                        <span style={{ marginLeft: 'auto', fontFamily: 'var(--font-mono)' }}>{attempts.toLocaleString()} attempts</span>
                    </div>
                )}
            </div>

            {wallets.length > 0 && (
                <div className="wallets-list fade-up">
                    {wallets.map((w, i) => (
                        <div key={w.id} className="wallet-card card">
                            <div className="wallet-header">
                                <span className="wallet-num">Wallet #{i + 1}</span>
                                <span className="badge badge-green">✓ Generated Locally</span>
                            </div>

                            {/* Address */}
                            <div className="field-row">
                                <div className="field-label">📍 Address <span className="safe-label">(Safe to share)</span></div>
                                <div className="copy-field">
                                    <span className="field-value mono">{w.address}</span>
                                    <button
                                        className="btn btn-ghost copy-btn"
                                        onClick={() => copyToClipboard(w.address, setCopied, `${w.id}-addr`)}
                                    >
                                        {copied === `${w.id}-addr` ? '✓' : 'Copy'}
                                    </button>
                                </div>
                            </div>

                            {/* Private Key */}
                            <div className="field-row">
                                <div className="field-label">🔑 Private Key <span className="danger-label">(Never share)</span></div>
                                <div className="copy-field">
                                    <span
                                        className={`field-value mono ${revealed[`${w.id}-pk`] ? '' : 'blurred'}`}
                                        onClick={() => toggleReveal(w.id, 'pk')}
                                        title="Click to reveal"
                                    >
                                        {w.privateKey}
                                    </span>
                                    <div style={{ display: 'flex', gap: 4, flexShrink: 0 }}>
                                        <button
                                            className="btn btn-ghost copy-btn"
                                            onClick={() => toggleReveal(w.id, 'pk')}
                                        >
                                            {revealed[`${w.id}-pk`] ? '🙈' : '👁'}
                                        </button>
                                        <button
                                            className="btn btn-ghost copy-btn"
                                            onClick={() => copyToClipboard(w.privateKey, setCopied, `${w.id}-pk`)}
                                        >
                                            {copied === `${w.id}-pk` ? '✓' : 'Copy'}
                                        </button>
                                    </div>
                                </div>
                            </div>

                            {/* Mnemonic */}
                            <div className="field-row">
                                <div className="field-label">📝 Seed Phrase <span className="danger-label">(Never share)</span></div>
                                <div className="copy-field mnemonic-field">
                                    <span
                                        className={`field-value mono ${revealed[`${w.id}-mn`] ? '' : 'blurred'}`}
                                        onClick={() => toggleReveal(w.id, 'mn')}
                                        title="Click to reveal"
                                    >
                                        {w.mnemonic}
                                    </span>
                                    <div style={{ display: 'flex', gap: 4, flexShrink: 0 }}>
                                        <button className="btn btn-ghost copy-btn" onClick={() => toggleReveal(w.id, 'mn')}>
                                            {revealed[`${w.id}-mn`] ? '🙈' : '👁'}
                                        </button>
                                        <button className="btn btn-ghost copy-btn" onClick={() => copyToClipboard(w.mnemonic, setCopied, `${w.id}-mn`)}>
                                            {copied === `${w.id}-mn` ? '✓' : 'Copy'}
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
                                <button className="btn btn-secondary" style={{ flex: 1 }} onClick={() => downloadJSON(w)}>
                                    ⬇️ Download JSON
                                </button>
                            </div>
                        </div>
                    ))}

                    <div className="alert alert-warning">
                        ⚠️ <strong>Important:</strong> Store your private key and seed phrase in a safe place OFFLINE. Anyone with these can access your wallet. Anonastr does not store or transmit any of this data.
                    </div>
                </div>
            )}
        </div>
    )
}
