import { useState } from 'react'
import { ethers } from 'ethers'
import { KeyIcon } from '../components/icons'
import './StealthWallet.css'

function copyToClipboard(text, setCopied, key) {
    navigator.clipboard.writeText(text).then(() => {
        setCopied(key)
        setTimeout(() => setCopied(''), 2000)
    })
}

export default function StealthWallet() {
    const [wallets, setWallets] = useState([])
    const [count, setCount] = useState(1)
    const [revealed, setRevealed] = useState({})
    const [copied, setCopied] = useState('')

    function generateWallets() {
        const generated = Array.from({ length: count }, () => {
            const w = ethers.Wallet.createRandom()
            return {
                id: crypto.randomUUID(),
                address: w.address,
                privateKey: w.privateKey,
                mnemonic: w.mnemonic.phrase,
            }
        })
        setWallets(generated)
        setRevealed({})
    }

    function toggleReveal(id, field) {
        setRevealed(r => ({ ...r, [`${id}-${field}`]: !r[`${id}-${field}`] }))
    }

    function downloadJSON(wallet) {
        const data = {
            address: wallet.address,
            privateKey: wallet.privateKey,
            mnemonic: wallet.mnemonic,
            generatedAt: new Date().toISOString(),
            warning: 'KEEP THIS FILE PRIVATE. NEVER SHARE IT. Generated by Anonastr — client-side only.',
        }
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `Anonastr-wallet-${wallet.address.slice(0, 8)}.json`
        a.click()
        URL.revokeObjectURL(url)
    }

    return (
        <div className="page fade-up">
            <h1 className="page-title">Stealth Wallet Generator</h1>
            <p className="page-subtitle">Generate fresh burner wallets entirely in your browser. Nothing ever leaves your device.</p>

            <div className="alert alert-warning" style={{ marginBottom: 24, alignItems: 'flex-start' }}>
                <KeyIcon style={{ width: 22, height: 22, flexShrink: 0, marginTop: 2, stroke: '#fcd34d' }} />
                <div>
                    <strong>100% Client-Side:</strong> All wallets are generated locally using cryptographically secure randomness. No data is sent to any server. Anonastr cannot see your keys.
                </div>
            </div>

            <div className="card">
                <div style={{ display: 'flex', gap: 12, alignItems: 'flex-end', flexWrap: 'wrap' }}>
                    <div className="input-group" style={{ flex: 1, marginBottom: 0 }}>
                        <label className="input-label">Number of Wallets</label>
                        <select
                            className="input"
                            value={count}
                            onChange={e => setCount(Number(e.target.value))}
                        >
                            {[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>{n} wallet{n > 1 ? 's' : ''}</option>)}
                        </select>
                    </div>

                    <button
                        className="btn btn-primary"
                        style={{ height: 50, minWidth: 140 }}
                        onClick={generateWallets}
                    >
                        <><KeyIcon color="black" style={{ width: 18, height: 18 }} /> Generate</>
                    </button>
                </div>
            </div>

            {wallets.length > 0 && (
                <div className="wallets-list fade-up">
                    {wallets.map((w, i) => (
                        <div key={w.id} className="wallet-card card">
                            <div className="wallet-header">
                                <span className="wallet-num">Wallet #{i + 1}</span>
                                <span className="badge badge-green">✓ Generated Locally</span>
                            </div>

                            {/* Address */}
                            <div className="field-row">
                                <div className="field-label">📍 Address <span className="safe-label">(Safe to share)</span></div>
                                <div className="copy-field">
                                    <span className="field-value mono">{w.address}</span>
                                    <button
                                        className="btn btn-ghost copy-btn"
                                        onClick={() => copyToClipboard(w.address, setCopied, `${w.id}-addr`)}
                                    >
                                        {copied === `${w.id}-addr` ? '✓' : 'Copy'}
                                    </button>
                                </div>
                            </div>

                            {/* Private Key */}
                            <div className="field-row">
                                <div className="field-label">🔑 Private Key <span className="danger-label">(Never share)</span></div>
                                <div className="copy-field">
                                    <span
                                        className={`field-value mono ${revealed[`${w.id}-pk`] ? '' : 'blurred'}`}
                                        onClick={() => toggleReveal(w.id, 'pk')}
                                        title="Click to reveal"
                                    >
                                        {w.privateKey}
                                    </span>
                                    <div style={{ display: 'flex', gap: 4, flexShrink: 0 }}>
                                        <button
                                            className="btn btn-ghost copy-btn"
                                            onClick={() => toggleReveal(w.id, 'pk')}
                                        >
                                            {revealed[`${w.id}-pk`] ? '🙈' : '👁'}
                                        </button>
                                        <button
                                            className="btn btn-ghost copy-btn"
                                            onClick={() => copyToClipboard(w.privateKey, setCopied, `${w.id}-pk`)}
                                        >
                                            {copied === `${w.id}-pk` ? '✓' : 'Copy'}
                                        </button>
                                    </div>
                                </div>
                            </div>

                            {/* Mnemonic */}
                            <div className="field-row">
                                <div className="field-label">📝 Seed Phrase <span className="danger-label">(Never share)</span></div>
                                <div className="copy-field mnemonic-field">
                                    <span
                                        className={`field-value mono ${revealed[`${w.id}-mn`] ? '' : 'blurred'}`}
                                        onClick={() => toggleReveal(w.id, 'mn')}
                                        title="Click to reveal"
                                    >
                                        {w.mnemonic}
                                    </span>
                                    <div style={{ display: 'flex', gap: 4, flexShrink: 0 }}>
                                        <button className="btn btn-ghost copy-btn" onClick={() => toggleReveal(w.id, 'mn')}>
                                            {revealed[`${w.id}-mn`] ? '🙈' : '👁'}
                                        </button>
                                        <button className="btn btn-ghost copy-btn" onClick={() => copyToClipboard(w.mnemonic, setCopied, `${w.id}-mn`)}>
                                            {copied === `${w.id}-mn` ? '✓' : 'Copy'}
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
                                <button className="btn btn-secondary" style={{ flex: 1 }} onClick={() => downloadJSON(w)}>
                                    ⬇️ Download JSON
                                </button>
                            </div>
                        </div>
                    ))}

                    <div className="alert alert-warning">
                        ⚠️ <strong>Important:</strong> Store your private key and seed phrase in a safe place OFFLINE. Anyone with these can access your wallet. Anonastr does not store or transmit any of this data.
                    </div>
                </div>
            )}
        </div>
    )
}
